vanilla_model.ALL:setVisible(false)
vanilla_model.ALL:setScale(0, 0, 0)
vanilla_model.RIGHT_ITEM:setVisible(true)
vanilla_model.RIGHT_ITEM:setScale(0.5, 0.5, 0.5)
models.Walterv5.ralts.body.torso.chest.arms.arm_right.arm_right2.RightItemPivot:setScale(0.5)